name: Propagate profile changes to SimulationCraft

on:
  push:
    branches:
      - master
    paths:
      - 'sims/owl/profiles/**'

jobs:
  propagate-profiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep "^sims/owl/profiles/" | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Checkout simc
        if: steps.changed-files.outputs.files != ''
        uses: actions/checkout@v4
        with:
          repository: simulationcraft/simc
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: './simc'

      - name: Setup commit
        if: steps.changed-files.outputs.files != ''
        run: |
          echo "COMMIT_AUTHOR=$(git log -1 --format=%aN)" >> $GITHUB_ENV
          echo "COMMIT_EMAIL=$(git log -1 --format=%aE)" >> $GITHUB_ENV
          git log -1 --pretty=format:"%B%ndreamgrove/Dreamgrove@%h" > commit_msg
          echo >> commit_msg
          echo >> commit_msg
          echo "Co-authored-by: Dreamgrove <dreamgrove@github.com>" >> commit_msg

      - name: Copy profile files
        if: steps.changed-files.outputs.files != ''
        env:
          PROFILE_FILES: ${{ steps.changed-files.outputs.files }}
        run: |
          # Copy each changed profile file to the corresponding location in simc
          for file in $PROFILE_FILES; do
            # Extract relative path within profiles directory
            relative_path=${file#sims/owl/profiles/}
            
            # Create directory structure if it doesn't exist
            mkdir -p "simc/profiles/$(dirname "$relative_path")"
            
            # Copy the file
            cp "$file" "simc/profiles/$relative_path"
            
            echo "Copied $file to simc/profiles/$relative_path"
          done

      - name: Commit profiles
        if: steps.changed-files.outputs.files != ''
        run: |
          git config --global user.name ${{ env.COMMIT_AUTHOR }}
          git config --global user.email ${{ env.COMMIT_EMAIL }}
          cd simc
          if [ -z "$(git status --porcelain)" ]; then
            echo "no changes to profiles"
          else
            git add .
            git commit -F ../commit_msg
            git push
          fi
